### ISSUE TITLE
I cant set set_kobo_token("this is a token value")

### ISSUE THREAD

**Issue by zxrey** [asitav-sen/KoboconnectR#1]
I install all dependences and the package, but when I try set the code:
set_kobo_token("this is a token value")
I get this message :
Error in set_kobo_token("b80c73109cb88e1f9b5ec94491f64badf3c3d907") : 
 function could not be found "set_kobo_token"

**Comment by asitav-sen** [comment]
Hi zxrey,
Thanks! Indeed, it doesn't work. This is because, I have changed it. Now the token needs to assigned manually. set_kobo_token was saving the token in the environment and I could not use externally (for e.g. in a deployed shiny app). 
So setting and retrieving of the tokens need to be done manually now.
The functions in [this page](https://github.com/asitav-sen/KoboconnectR/blob/main/R/depreciated.R) are depreciated.

**Comment by zxrey** [comment]
Thanks for the aswer!
I try again but I get a list of list when I code:

kobotools_kpi_data(
  assetid,
  url = "kobo.humanitarianresponse.info",
  forma = "json",
  tokenvalue = "tokenvalue"
)

And I have a question, can I get xlsx form or only works for csv?

**Comment by asitav-sen** [comment]
Hi zxrey,

This is how a `json` format looks like. Unfortunately there is no easy way to automatically convert it to any other format. This is because the patterns are not limited. For e.g. in your case you have list inside list. Others may have list inside list inside list. Or even more complicated like 5 lists where each list have different numbers of lists inside.
These list inside lists are called nested json.
I recommend you start with [this simple tutorial](https://www.tutorialspoint.com/r/r_json_files.htm) first. This covers `non-nested` jsons. Then read out `how to extract data from nested json in R`, in google. For example [this is one](https://community.rstudio.com/t/how-to-read-multilevel-json-data-and-convert-to-data-frame-in-r/7571/10).

**Comment by asitav-sen** [comment]
> Thanks for the aswer! I try again but I get a list of list when I code:
> 
> kobotools_kpi_data( assetid, url = "kobo.humanitarianresponse.info", forma = "json", tokenvalue = "tokenvalue" )
> 
> And I have a question, can I get xlsx form or only works for csv?

Hi [zxrey](https://github.com/zxrey): I have included function to create and download exports. Now you can download csv and xls files directly. Please be mindful that exports capture the survey data at a given point in time. It does not automatically updates when new data is entered in the survey.

**Comment by asitav-sen** [comment]
@zxrey Glad that you liked it. Sorry for the trouble to add few more steps. I am working on a version where you will not need the additional codes. Will update you soon.

**Comment by zxrey** [comment]
Sorry l found a problem in the function:
new_export_url <- kobo_export_create(url="kobo.humanitarianresponse.info", uname="zxreynaldo", pwd="+-CHEVEREWOW",
                   assetid="a9mw2GTzq8fBUWBBFkvyvF", type= "xls", all="false", lang="_default",
                   hierarchy="false", **include_grp="true"**,grp_sep="/")

l tried to change this part and put "false" and doesn't work **include grep="false"**

**Comment by zxrey** [comment]
Yes still download but l mean in the page doesn't change the option:

![image](https://user-images.githubusercontent.com/68795117/161804854-78348007-84b9-4899-99db-55f601de2773.png)
That should have change when we change that **include_grp="false**

**Comment by asitav-sen** [comment]
Thanks for pointing this out.
This could be a shortcoming of the API itself. I will test a few times and get back to you. Thanks for pointing out. Much appreciated.
